export const mockContas = [
  {
    id: '1',
    descricao: 'Aluguel',
    valor: 1500,
    dataVencimento: new Date().toISOString().split('T')[0],
    status: 'pendente',
    categoria: 'moradia',
    observacoes: null,
    recorrente: true,
    intervaloRecorrencia: 'mensal',
    recorrenciaAtiva: true,
    parcelado: false,
    totalParcelas: null,
    parcelaAtual: null,
    grupoParcelamento: null,
    criadoEm: new Date(),
    atualizadoEm: new Date(),
  },
  {
    id: '2',
    descricao: 'Conta de água',
    valor: 150,
    dataVencimento: '2026-05-05',
    status: 'pendente',
    categoria: 'utilidades',
    observacoes: null,
    recorrente: true,
    intervaloRecorrencia: 'mensal',
    recorrenciaAtiva: true,
    parcelado: false,
    totalParcelas: null,
    parcelaAtual: null,
    grupoParcelamento: null,
    criadoEm: new Date(),
    atualizadoEm: new Date(),
  },
  {
    id: '3',
    descricao: 'Conta de luz',
    valor: 200,
    dataVencimento: '2026-05-10',
    status: 'pago',
    categoria: 'utilidades',
    observacoes: null,
    recorrente: true,
    intervaloRecorrencia: 'mensal',
    recorrenciaAtiva: true,
    parcelado: false,
    totalParcelas: null,
    parcelaAtual: null,
    grupoParcelamento: null,
    criadoEm: new Date(),
    atualizadoEm: new Date(),
  },
];

export const mockConfig = {
  id: 'main',
  saldoInicial: 5000,
  nomeUsuario: 'Léo Silva',
  criadoEm: new Date(),
  atualizadoEm: new Date(),
};
